function xZZZ(){this.window=window;this.________V();this.________W();this.________X();this.________Y();this.________Z();this._______$Z();this._______aZ();this._______bZ();this._______cZ();this._______dZ();this.________M();this._______eZ();this._______u();_.a.___SZ.EZZ();}
xZZZ.prototype.________W=function(){this._______fZ=UZZ(v._gZ());v._rZ(this._______fZ,{position:"absolute",zIndex:3,bottom:0,right:0});}
xZZZ.prototype._______eZ=function(){this._______gZ=new ____YZZZ();this._______gZ.____ZZZZ._zZZ(this,function(data){var _______hZ=new ____XZZ(this._______fZ,data);});}
xZZZ.prototype.________M=function(){v.w(window,"beforeunload",function(){var _______iZ=[];this._______jZ.xZZZ._U(function(_Q){if(_Q._cZ===_______kZ&&_Q.___bZZZZ!==null&&_Q.___bZZZZ._hZZZZZZ.__wZ()&&_Q.___bZZZZ._gZZZZZZ.__wZ()){_______iZ.push(_Q.___bZZZZ.sZZ);}});if(_______iZ.length>0){____v.____X(G("/xhr/quit.php"),_______iZ);}},this);}
xZZZ.prototype._______lZ=function(id){var ___n=null;this._______jZ.xZZZ._U(function(_Q){if(_Q._cZ===_______kZ&&_Q.___bZZZZ!==null&&_Q.___bZZZZ.sZZ===id){___n=_Q.___bZZZZ;return true;}});return ___n;}
xZZZ.prototype._______dZ=function(){this.__oZZ=new __oZZ();this.__oZZ.___m._zZZ(this,function(data,sender){if(___x(data.o)){var ___jZZZ;for(var O=0;O<data.o.length;O++){___jZZZ=data.o[O];switch(___jZZZ["type"]){case __g:{var ___n=this._______lZ(___jZZZ["subject"]);if(___n!==null){___n.________i(___jZZZ["sender"]);}
break;}
case __a:{var ___n=this._______lZ(___jZZZ["subject"]);if(___n!==null){___n.________j(___jZZZ["sender"]);}
break;}
case __e:{var ___n=this._______lZ(___jZZZ["subject"]);if(___n!==null){___n.________k(___jZZZ["sender"]);}
break;}
case __f:{var ___n=this._______lZ(___jZZZ["subject"]);if(___n!==null){___n.________l(___jZZZ["sender"]);}
break;}
case __$:{var ___n=this._______lZ(___jZZZ["subject"]);if(___n!==null){___n.________o(___jZZZ["sender"],___jZZZ["body"]);}
break;}}}}});}
xZZZ.prototype._______cZ=function(){_.a.___LZ._zZZ(this,function(data){var CZZZ=null;this._______jZ.xZZZ._U(function(_Q){if(_Q._cZ===_______kZ&&_Q.___bZZZZ!==null&&_Q.___bZZZZ.sZZ===data.sZZ){CZZZ=_Q;return true;}});if(CZZZ===null){CZZZ=this._______jZ._P(_______kZ);_.j.____s(function(){CZZZ.____WZZ();CZZZ.___bZZZZ._JZZZZZZ(data.sZZ);});}
else{CZZZ._rZZ.EZZZ(CZZZ);}});_.a.___KZ._zZZ(this,function(data){var CZZZ=null;this._______jZ.xZZZ._U(function(_Q){if(_Q._cZ===_______kZ&&_Q.___bZZZZ!==null&&_Q.___bZZZZ.sZZ===data.sZZ){CZZZ=_Q;return true;}});if(CZZZ===null){CZZZ=this._______jZ._P(_______kZ);_.j.____s(function(){CZZZ.____WZZ();CZZZ.___bZZZZ._JZZZZZZ(data.sZZ);});CZZZ.___bZZZZ._EZZZ._zZZ(this,(function(game_id,colour){return function(data,sender){sender._JZZZZZ(game_id,colour);};})(data.___UZ,data.___VZ));}
else{CZZZ.___bZZZZ._JZZZZZ(data.___UZ,data.___VZ);CZZZ._rZZ.EZZZ(CZZZ);}});}
xZZZ.prototype.________V=function(){var self=this;this._______mZ=false;this._______nZ=false;this._______oZ=[];this._______pZ={"l":_______kZ,"e":_______qZ};this._______jZ=new sZZZ(_hZ("#tab_bar"),_hZ("#tab_body"),"tab_button","tab_button_on");this._______jZ._EZZ._LZZ.BZZ(1);this._______jZ.AZZZ._zZZ(this,function(data,sender){for(var _F in this._______pZ){if(data._lZZ._cZ===this._______pZ[_F]){data._lZZ.dZZ=_F;break;}}
if(data._lZZ.dZZ!==null){data._lZZ.bZZ._zZZ(this,function(data,sender){if(!this._______nZ){var K=sender.dZZ+data.sZZ;var _______rZ=false;for(var O=0;O<this._______oZ.length;O++){if(this._______oZ[O]===K){_______rZ=true;break;}}
if(!_______rZ){this._______oZ.push(K);this._______sZ();}}});data._lZZ.cZZ._zZZ(this,function(data,sender){if(!this._______nZ){var K=sender.dZZ+data.sZZ;for(var O=0;O<this._______oZ.length;O++){if(this._______oZ[O]===K){this._______oZ.splice(O,1);O--;}}
this._______sZ();}});}});v.w(window,"hashchange",function(){if(!self._______mZ){self._______tZ();}});this._______uZ=this._______jZ._P(_______vZ);this._______uZ._uZZ=false;this._______tZ();}
xZZZ.prototype.________X=function(){var tables=_.Request["page"]["tables"];var id;var _______rZ;for(var O=0;O<tables.length;O++){id=tables[O];_______rZ=false;this._______jZ.xZZZ._U(function(_Q){if(_Q._cZ===_______kZ&&_Q.___bZZZZ!==null&&_Q.___bZZZZ.sZZ===id){_______rZ=true;return true;}});if(!_______rZ){var CZZZ=this._______jZ._P(_______kZ);CZZZ.____WZZ();CZZZ.___bZZZZ._JZZZZZZ(id);}}}
xZZZ.prototype.________Y=function(){this._______wZ={_______xZ:_hZ("#new_live"),_______yZ:_hZ("#new_custom"),_______zZ:_hZ("#new_analysis")};v.w(this._______wZ._______xZ,"click",function(){_.a.zZZ._P(this._______wZ._______xZ);if(this._______AZ.HZZ.__wZ()){this._______AZ.HZZ.BZZ(false);}
else{var _kZ=v._qZ(this._______wZ._______xZ);var _______Z=[this._______wZ._______xZ.offsetWidth,this._______wZ._______xZ.offsetHeight];this._______AZ.HZZ.BZZ(true);this._______AZ.__OZ(_kZ[_oZ]+Math.round(_______Z[_oZ]/2),_kZ[_pZ]+_______Z[_pZ]+5);this._______BZ.gZZZZZZ();}},this);v.w(this._______wZ._______yZ,"click",function(){_.a.zZZ._P(this._______wZ._______yZ);if(this._______CZ.HZZ.__wZ()){this._______CZ.HZZ.BZZ(false);}
else{var _kZ=v._qZ(this._______wZ._______yZ);var _______Z=[this._______wZ._______yZ.offsetWidth,this._______wZ._______yZ.offsetHeight];this._______CZ.HZZ.BZZ(true);this._______CZ.__OZ(_kZ[_oZ]+Math.round(_______Z[_oZ]/2),_kZ[_pZ]+_______Z[_pZ]+5);}},this);v.w(this._______wZ._______zZ,"click",function(){this._______jZ._P(_______qZ).____WZZ();},this);}
xZZZ.prototype.________Z=function(){this._______CZ=new __xZ(__FZ,{__AZ:8,RZZ:220,__CZ:"#808080"});this._______CZ.HZZ.BZZ(false);this.____VZZ=new ____VZZ(this._______CZ.__KZ);this.____VZZ.____WZZ._zZZ(this,function(data){var CZZZ=this._______jZ._P(_______kZ);CZZZ.____WZZ();CZZZ.___bZZZZ._cZ.BZZ(data._cZ);CZZZ.___bZZZZ.__QZZ();this._______CZ.HZZ.BZZ(false);});_.a.___JZ._zZZ(this,function(){if(!_.a.zZZ.fZ(this._______wZ._______yZ)&&!_.a.zZZ.fZ(this._______CZ)){this._______CZ.HZZ.BZZ(false);}});_.a.___NZ._zZZ(this,function(){this._______CZ.HZZ.BZZ(false);});}
xZZZ.prototype._______$Z=function(){this._______AZ=new __xZ(__FZ,{__AZ:8,RZZ:220,__CZ:"#808080"});this._______AZ.HZZ.BZZ(false);this._______BZ=new qZZZZZZ(this._______AZ.__KZ);this._______BZ.RZZ.BZZ(220);this._______BZ._KZZ.BZZ(5);this._______BZ.wZZZZZZ._zZZ(this,function(data,sender){if(data.VZZZZZZ===___aZZZ.________g){var CZZZ=this._______jZ._P(_______kZ);CZZZ.____WZZ();CZZZ.___bZZZZ._JZZZZZZ(data.___bZZZZ);CZZZ.___bZZZZ.__DZZZZZ=sender.___aZZZ;this._______AZ.HZZ.BZZ(false);}});_.a.___JZ._zZZ(this,function(){if(!_.a.zZZ.fZ(this._______wZ._______xZ)&&!_.a.zZZ.fZ(this._______AZ)){if(!this._______BZ.xZZZZZZ.__wZ()){this._______AZ.HZZ.BZZ(false);}}});_.a.___NZ._zZZ(this,function(){this._______AZ.HZZ.BZZ(false);});}
xZZZ.prototype._______bZ=function(){}
xZZZ.prototype._______aZ=function(){var _______DZ=new __kZZ(ZZ,_.Request["page"]["main_page_update"]);_______DZ.__nZZ._zZZ(this,function(){_.j.____r();window.location.href=G("/");});}
xZZZ.prototype._______tZ=function(){this._______nZ=true;var hash=window.location.hash;if(hash.indexOf("!")===1&&hash.length>2){this._______oZ=hash.substr(2).split(",");var K,type,id,CZZZ;var _______rZ;for(var O=0;O<this._______oZ.length;O++){K=this._______oZ[O];type=K.substr(0,1);id=parseInt(K.substr(1));if((type in this._______pZ)&&_sZ(id)){_______rZ=false;this._______jZ.xZZZ._U(function(_Q){if(_Q.dZZ===type&&_Q.___bZZZZ!==null&&_Q.___bZZZZ.sZZ===id){_______rZ=true;return true;}},this);if(!_______rZ){CZZZ=this._______jZ._P(this._______pZ[type]);CZZZ.____WZZ();CZZZ.___bZZZZ._JZZZZZZ(id);}}}
this._______jZ.xZZZ._U(function(_Q){if((_Q.dZZ in this._______pZ)&&_Q.___bZZZZ!==null){var _______EZ=false;K=_Q.dZZ+_Q.___bZZZZ.sZZ;for(var O=0;O<this._______oZ.length;O++){if(this._______oZ[O]===K){_______EZ=true;break;}}
if(!_______EZ){this._______jZ.FZZZ(_Q);}}},this);}
else{this._______oZ=[];}
this._______nZ=false;}
xZZZ.prototype._______sZ=function(){this._______mZ=true;window.location.hash="#!"+this._______oZ.join(",");this._______mZ=false;}
xZZZ.prototype._______u=function(){_.j.____l.BZZ(G("/xhr/updates.php"));_.j.____q();}
var ________O;_.g._zZZ(this,function(){________O=new xZZZ();});