var _$ZZZ={______I:function(______J){return(______J%2==1)?kZZZZ:_____d;},_RZZZ:function(colour){return ___oZ(!colour);},______K:function(game_id){return ___oZ(!game_id);},______L:function(______J){return Math.floor(______J/2);},______M:function(______J){return _$ZZZ.______L(______J)+1;},______N:function(______M){return(______M-1)*2;},______O:function(colour){return[".","..."][colour];},jZZZZ:function(result,colour){if(result===__A){return ______P;}
if(colour===_____d){return result===__B?______Q:______R;}
if(colour===kZZZZ){return result===__z?______Q:______R;}},______S:function(______J){return ______J%2;},type:function(piece){return piece&______T;},colour:function(piece){return piece>>______U;},piece:function(type,colour){return(colour<<______U)|type;},__hZZZ:function(wZZZZ){return(wZZZZ>-1&&wZZZZ<64);},______V:function(____CZ,____BZ){return ____BZ*8+____CZ;},______W:function(wZZZZ){return(!(((wZZZZ%2)+(Math.floor(wZZZZ/8)%2))%2))-0;},______X:function(colour){var fen={w:"white",b:"black"};var name={white:"white",black:"white"};var ______Y=[];______Y[_____d]="white"
______Y[kZZZZ]="black";if(colour in fen){return fen[colour];}
else if(colour in name){return name[colour];}
else{return ______Y[colour];}},______Z:function(colour){var fen={w:____RZ,b:____QZ};var name={white:____RZ,black:____QZ};var ______Y=[];______Y[_____d]=____RZ;______Y[kZZZZ]=____QZ;if(colour in fen){return fen[colour];}
else if(colour in name){return name[colour];}
else{return ______Y[colour];}},____SZ:function(colour){var fen={w:_____d,b:kZZZZ};var name={white:_____d,black:kZZZZ};var ______Y=[];______Y[_____d]=_____d;______Y[kZZZZ]=kZZZZ;if(colour in fen){return fen[colour];}
else if(colour in name){return name[colour];}
else{return ______Y[colour];}},__mZZZ:function(wZZZZ,colour){return(colour===kZZZZ?63-wZZZZ:wZZZZ);},__PZ:function(wZZZZ){return(wZZZZ%8);},__QZ:function(wZZZZ){return((wZZZZ-_$ZZZ.__PZ(wZZZZ))/8);},__BZZZ:function(wZZZZ){return _____P.substr(wZZZZ%8,1);},_____$Z:function(wZZZZ){return ____EZ.substr(((wZZZZ-(wZZZZ%8))/8),1);},_____i:function(wZZZZ){return _____P.substr(wZZZZ%8,1);},____zZ:function(wZZZZ){return ____EZ.substr(((wZZZZ-(wZZZZ%8))/8),1);},wZZZZ:function(wZZZZ){return _$ZZZ.__WZZZ([_____P.indexOf(wZZZZ.charAt(_oZ)),____EZ.indexOf(wZZZZ.charAt(_pZ))]);},__qZZZ:function(wZZZZ){return _$ZZZ._____i(wZZZZ)+_$ZZZ.____zZ(wZZZZ);},__jZZZ:function(wZZZZ){var __PZ=wZZZZ%8,__QZ=(wZZZZ-__PZ)/8;return[__PZ,__QZ];},__WZZZ:function(_____aZ){return(_____aZ[_pZ]*8)+_____aZ[_oZ];},_____bZ:function(a,b){return Math.abs(a-b);},_____cZ:function(a,b){return _$ZZZ._____i(a)===_$ZZZ._____i(b);},_____dZ:function(a,b){return _$ZZZ.____zZ(a)===_$ZZZ.____zZ(b);},__vZZZ:function(type,__iZZZ,__kZZZ){var _____eZ=[];var _____fZ=[_oZ,_pZ];for(var O=0;O<_____fZ.length;O++){_____eZ[_____fZ[O]]=_$ZZZ._____bZ(__iZZZ[_____fZ[O]],__kZZZ[_____fZ[O]]);}
if(_____eZ[_oZ]===0&&_____eZ[_pZ]===0){return false;}
switch(type){case __DZZZ:{return((_____eZ[_oZ]===2&&_____eZ[_pZ]===1)||(_____eZ[_oZ]===1&&_____eZ[_pZ]===2));}
case _uZZZZ:{return(_____eZ[_oZ]===_____eZ[_pZ]);}
case __LZZZ:{return(_____eZ[_oZ]===0||_____eZ[_pZ]===0);}
case vZZZZ:{return(_$ZZZ.__vZZZ(__LZZZ,__iZZZ,__kZZZ)||_$ZZZ.__vZZZ(_uZZZZ,__iZZZ,__kZZZ));}
case GZZZZ:{return((_____eZ[_oZ]===1||_____eZ[_oZ]===0)&&(_____eZ[_pZ]===1||_____eZ[_pZ]===0));}}
return false;},__JZZZ:function(fs,ts){return(ts-fs===8);},__HZZZ:function(fs,ts){return(fs>7&&fs<16&&ts-fs===16);},__zZZZ:function(fs,ts){var __iZZZ=_$ZZZ.__jZZZ(fs);var __kZZZ=_$ZZZ.__jZZZ(ts);return(__kZZZ[_pZ]-__iZZZ[_pZ]===1&&_$ZZZ._____bZ(__kZZZ[_oZ],__iZZZ[_oZ])===1);},__CZZZ:function(ts){return(ts>55);},__KZZZ:function(fs,ts){return _$ZZZ.__WZZZ([_$ZZZ.__PZ(ts),_$ZZZ.__QZ(fs)]);},_____gZ:function(fs,ts){var PZZZZ=[4,60];var QZZZZ;var _v,SZZZZ;var _____hZ=[ZZZZZ,______];var TZZZZ;for(var O=0;O<PZZZZ.length;O++){_v=PZZZZ[O];if(fs===_v){QZZZZ=[_v+2,_v-2];for(var RZZZZ=_____f;RZZZZ<=_____g;RZZZZ++){SZZZZ=QZZZZ[RZZZZ];if(ts===SZZZZ){TZZZZ=[[SZZZZ+1,SZZZZ-1],[SZZZZ-2,SZZZZ+1]];return{RZZZZ:RZZZZ,_____iZ:TZZZZ[RZZZZ][0],_____jZ:TZZZZ[RZZZZ][1],_____hZ:_____hZ[RZZZZ]};}}}}
return false;},_____kZ:function(__iZZZ,__kZZZ){return _$ZZZ._____bZ(__iZZZ[_oZ],__kZZZ[_oZ]);},__VZZZ:function(fs,ts,_____lZ){var _s=[];var ___gZ=fs;fs=Math.min(fs,ts);ts=Math.max(___gZ,ts);var __iZZZ=_$ZZZ.__jZZZ(fs);var __kZZZ=_$ZZZ.__jZZZ(ts);var _____mZ=_$ZZZ._____bZ(fs,ts);var ____bZ;if(_____lZ){_s.push(fs);}
if(_$ZZZ.__vZZZ(_uZZZZ,__iZZZ,__kZZZ)){var _____nZ=_$ZZZ._____kZ(__iZZZ,__kZZZ);if(_____nZ>0){____bZ=_____mZ/_____nZ;for(var _v=fs+____bZ;_v<ts;_v+=____bZ){_s.push(_v);}}}
else if(_$ZZZ.__vZZZ(__LZZZ,__iZZZ,__kZZZ)){____bZ=_____mZ>7?8:1;for(var _v=fs+____bZ;_v<ts;_v+=____bZ){_s.push(_v);}}
if(_____lZ){_s.push(ts);}
return _s;},__pZZZ:function(__SZZ,fs,ts){var _____oZ=_$ZZZ.__VZZZ(fs,ts);for(var O=0;O<_____oZ.length;O++){if(__SZZ[_____oZ[O]]!==zZZZZ){return true;}}
return false;},__aZZZ:function(_UZZZ,wZZZZ,colour){var __iZZZ=_$ZZZ.__jZZZ(wZZZZ);var __$ZZZ=[];switch(_UZZZ){case _tZZZ:{var _____pZ=_$ZZZ.__mZZZ(wZZZZ,colour);if(_____pZ<16){__$ZZZ.push(_$ZZZ.__mZZZ(_____pZ+16,colour));}
var _____qZ=_$ZZZ.__jZZZ(_____pZ);var _____rZ,_____sZ;for(var _____tZ=-1;_____tZ<2;_____tZ++){_____rZ=_____qZ[_oZ]+_____tZ;_____sZ=_____qZ[_pZ]+1;if(_____rZ>-1&&_____rZ<8&&_____sZ>-1&&_____sZ<8){__$ZZZ.push(_$ZZZ.__mZZZ(_$ZZZ.__WZZZ([_____rZ,_____sZ]),colour));}}
break;}
case __DZZZ:{var _____uZ=[-1,-1,1,1,-2,-2,2,2];var _____vZ=[-2,2,-2,2,1,-1,1,-1];var _____rZ,_____sZ;for(var O=0;O<8;O++){_____rZ=__iZZZ[_oZ]+_____uZ[O];_____sZ=__iZZZ[_pZ]+_____vZ[O];if(_____rZ>-1&&_____rZ<8&&_____sZ>-1&&_____sZ<8){__$ZZZ.push(_$ZZZ.__WZZZ([_____rZ,_____sZ]));}}
break;}
case _uZZZZ:{var _____bZ=[1,-1];for(var _____wZ=0;_____wZ<_____bZ.length;_____wZ++){for(var _____xZ=0;_____xZ<_____bZ.length;_____xZ++){var _____aZ=[__iZZZ[_oZ],__iZZZ[_pZ]];while(_____aZ[_oZ]>-1&&_____aZ[_oZ]<8&&_____aZ[_pZ]>-1&&_____aZ[_pZ]<8){_____aZ[_oZ]+=_____bZ[_____wZ];_____aZ[_pZ]+=_____bZ[_____xZ];if(_____aZ[_oZ]>-1&&_____aZ[_oZ]<8&&_____aZ[_pZ]>-1&&_____aZ[_pZ]<8){__$ZZZ.push(_$ZZZ.__WZZZ([_____aZ[_oZ],_____aZ[_pZ]]));}}}}
break;}
case __LZZZ:{var _____yZ;for(var O=0;O<8;O++){_____yZ=[(__iZZZ[_pZ]*8)+O,__iZZZ[_oZ]+(O*8)];for(var _v=0;_v<_____yZ.length;_v++){if(_____yZ[_v]!==wZZZZ){__$ZZZ.push(_____yZ[_v]);}}}
break;}
case vZZZZ:{var ____BZ=_$ZZZ.__aZZZ(__LZZZ,wZZZZ,colour);var b=_$ZZZ.__aZZZ(_uZZZZ,wZZZZ,colour);__$ZZZ=[].concat(____BZ,b);break;}
case GZZZZ:{var _____rZ,_____sZ;for(var _____tZ=-1;_____tZ<2;_____tZ++){_____rZ=__iZZZ[_oZ]+_____tZ;if(_____rZ>-1&&_____rZ<8){for(var _____zZ=-1;_____zZ<2;_____zZ++){_____sZ=__iZZZ[_pZ]+_____zZ;if(_____sZ>-1&&_____sZ<8){__$ZZZ.push(_$ZZZ.__WZZZ([_____rZ,_____sZ]));}}}}
var _____tZ=[-2,2];for(var O=0;O<_____tZ.length;O++){_____rZ=__iZZZ[_oZ]+_____tZ[O];if(_____rZ>-1&&_____rZ<8){__$ZZZ.push(_$ZZZ.__WZZZ([_____rZ,__iZZZ[_pZ]]));}}
break;}}
return __$ZZZ;},_____AZ:function(__SZZ,type,wZZZZ,colour){var _____BZ=[];var piece=_$ZZZ.piece(type,colour);var _____yZ=_$ZZZ.__aZZZ(type,wZZZZ,colour);var _v;for(var O=0;O<_____yZ.length;O++){_v=_____yZ[O];if(__SZZ[_v]===piece&&!_$ZZZ.__pZZZ(__SZZ,wZZZZ,_v)){_____BZ.push(_v);}}
return _____BZ;},_____CZ:function(__SZZ,wZZZZ,colour){var piece=_$ZZZ.piece(_tZZZ,colour);var _____DZ=___oZ(!colour);var _____pZ=_$ZZZ.__mZZZ(wZZZZ,_____DZ);var _____qZ=_$ZZZ.__jZZZ(_____pZ);var _____tZ=[-1,1];var _____eZ,_____rZ,_____sZ,_v;var _____BZ=[];for(var O=0;O<_____tZ.length;O++){_____eZ=_____tZ[O];_____rZ=_____qZ[_oZ]+_____eZ;_____sZ=_____qZ[_pZ]+1;if(_____rZ>-1&&_____rZ<8&&_____sZ>-1&&_____sZ<8){_v=_$ZZZ.__mZZZ(_$ZZZ.__WZZZ([_____rZ,_____sZ]),_____DZ);if(__SZZ[_v]===piece){_____BZ.push(_v);}}}
return _____BZ;},_____EZ:function(__SZZ,wZZZZ,colour){var piece=_$ZZZ.piece(GZZZZ,colour);var _____aZ=_$ZZZ.__jZZZ(wZZZZ);var _____rZ,_____sZ,_v;var _____BZ=[];for(var _____tZ=-1;_____tZ<2;_____tZ++){_____rZ=_____aZ[_oZ]+_____tZ;if(_____rZ>-1&&_____rZ<8){for(var _____zZ=-1;_____zZ<2;_____zZ++){_____sZ=_____aZ[_pZ]+_____zZ;if(_____sZ>-1&&_____sZ<8){_v=_$ZZZ.__WZZZ([_____rZ,_____sZ]);if(__SZZ[_v]===piece){_____BZ.push(_v);}}}}}
return _____BZ;},_iZZZZ:function(__SZZ,wZZZZ,colour){var _____BZ=[];var type=[__DZZZ,_uZZZZ,__LZZZ,vZZZZ];for(var O=0;O<type.length;O++){_____BZ=_____BZ.concat(_$ZZZ._____AZ(__SZZ,type[O],wZZZZ,colour));}
_____BZ=_____BZ.concat(_$ZZZ._____CZ(__SZZ,wZZZZ,colour));_____BZ=_____BZ.concat(_$ZZZ._____EZ(__SZZ,wZZZZ,colour));return _____BZ;},____MZ:function(___eZ,colour,RZZZZ,_____J){var __PZZ=1<<(colour*2+RZZZZ);return _____J?(___eZ|__PZZ):(~__PZZ)&___eZ;},____OZ:function(___eZ,colour,RZZZZ){return(___eZ>>(colour*2+RZZZZ))&1;},__sZZZ:function(__SZZ,type,colour,fs,ts){var K="";var _____FZ=_$ZZZ._____AZ(__SZZ,type,ts,colour);var _v;if(_____FZ.length>1){var _____GZ={_____i:"",____zZ:""};for(var O=0;O<_____FZ.length;O++){_v=_____FZ[O];if(_v!==fs){if(_$ZZZ.____zZ(_v)===_$ZZZ.____zZ(fs)){_____GZ._____i=_$ZZZ._____i(fs);}
if(_$ZZZ._____i(_v)===_$ZZZ._____i(fs)){_____GZ.____zZ=_$ZZZ.____zZ(fs);}}}
K=_____GZ._____i+_____GZ.____zZ;if(K.length===0){K=_$ZZZ._____i(fs);}}
return K;},_____HZ:function(_F,SZZZZ,___pZ){return Math.round((_F+(((_F>-1&&_F<2100)?32:((_F>2099&&_F<2400)?24:16))*(___pZ-(1/(1+(Math.pow(10,((SZZZZ-_F)/400)))))))));}}