function ___yZZZZ(FZZZZZ){_pZZ.iZZ(this);this._M=[];this._GZZZ=FZZZZZ;this.___zZZZZ=new h(this);this.___m=new h(this);this.__fZZ();this.__gZZ();}
___yZZZZ.prototype.__fZZ=function(){____v.____T(G("/xhr/premove_list.php"),function(data){this.___zZZZZ.t();this.________x(data);this.___m.t();},{"gid":this._GZZZ.___eZZZZ},this);}
___yZZZZ.prototype.__gZZ=function(){_.j.____f._zZZ(this,function(__hZZ){var colour,UZZZZZZZ;var move_index=-1;UZZZZZZZ=(this._GZZZ.___bZZZZ.___gZZZZ!==null);if(UZZZZZZZ){colour=this._GZZZ.___bZZZZ.___gZZZZ.___VZ;if(this._GZZZ._HZZZ.___WZZ.___XZZ._N>0){move_index=this._GZZZ._HZZZ.___WZZ.hZZZZZ.rZZZZZ;}
__hZZ.____L(this,__W,{"gid":this._GZZZ.___eZZZZ,"move_index":move_index,"colour":colour});}});_.j.____g._zZZ(this,function(__hZZ){var data=__hZZ.____N(this);if(data!==null){this.___zZZZZ.t();this.________x(data);this.___m.t();}});}
___yZZZZ.prototype._P=function(_UZZZ){this.___zZZZZ.t();this._M.push(_UZZZ);____v.____T("/xhr/premove_push.php",function(____x){if(!____x["success"]){this.___zZZZZ.t();while(this._M.length>0&&___rZ(this._M).rZZZZZ>=____x["move_index"]){this._M.pop();}
this.___m.t();}},{"gid":this._GZZZ.___eZZZZ,"fs":_UZZZ.__fZZZ,"ts":_UZZZ.__gZZZ,"move_index":_UZZZ.rZZZZZ,"promote_to":_UZZZ.__GZZZ},this);this.___m.t();}
___yZZZZ.prototype._zZZZZ=function(){if(this._M.length>0){this.___zZZZZ.t();var _UZZZ=this._M.pop();____v.____T(G("/xhr/premove_clear.php"),function(____x){if(____x===false){this.___zZZZZ.t();this._M.push(_UZZZ);this.___m.t();}},{"gid":this._GZZZ.___eZZZZ,"move_index":_UZZZ.rZZZZZ},this);this.___m.t();}}
___yZZZZ.prototype.aZ=function(){var ________y=o.I(this._M);this.___zZZZZ.t();this._M=[];if(this._M.length>0){____v.____T(G("/xhr/premove_clear.php"),function(____x){if(____x===false){this.___zZZZZ.t();this._M=o.p(________y);this.___m.t();}},{"gid":this._GZZZ.___eZZZZ},this);}
this.___m.t();}
___yZZZZ.prototype.________x=function(___n){var ___p,_UZZZ;if(___x(___n)){this._M=[];for(var O=0;O<___n.length;O++){___p=___n[O];_UZZZ={__fZZZ:___p["fs"],__gZZZ:___p["ts"],__GZZZ:___p["promote_to"],rZZZZZ:___p["move_index"]};this._M.push(_UZZZ);}}}
___yZZZZ.prototype.__jZZ=function(){this._DZZ();}