<?php
/*
Codes from database "bugs".

Generated by /home/gus/bin/dbcodes at 22:45, 28/12/2012.
*/

/*
Code types
*/

define("ACTION_TYPE", "ACT");

/*
Codes
*/

define("ACTION_TYPE_RESOLVED", "RES");
define("ACTION_TYPE_UNRESOLVED", "UN");
define("ACTION_TYPE_NONISSUE", "NON");

define("_CREATE_BUGS", "CRT");
define("_MODIFY_BUGS", "MOD");
define("_DELETE_BUGS", "DEL");
define("_ADD_USERS", "ADD");
define("_REMOVE_USERS", "REM");
?>