function cZZZZ(parent){hZZ.iZZ(this,parent);this._HZZZ=null;this.___MZZZ="/img/buttons";this.width=100;this.RZZ=new lZZ(this,function(){return this.width;},function(value){this.width=value;this.mZZ();});this.nZZ();}
cZZZZ.prototype.nZZ=function(){this.TZZ=UZZ(this.pZZ);v._WZ(this.TZZ,"hist_ctrl_buttons");this.___NZZZ=new __TZ(this.TZZ,23,20,this.___MZZZ+"/hist_ctrl_first.png");this.___OZZZ=new __TZ(this.TZZ,23,20,this.___MZZZ+"/hist_ctrl_prev5.png");this.___PZZZ=new __TZ(this.TZZ,23,20,this.___MZZZ+"/hist_ctrl_prev.png");this.___QZZZ=new __TZ(this.TZZ,23,20,this.___MZZZ+"/hist_ctrl_next.png");this.___RZZZ=new __TZ(this.TZZ,23,20,this.___MZZZ+"/hist_ctrl_next5.png");this.___SZZZ=new __TZ(this.TZZ,23,20,this.___MZZZ+"/hist_ctrl_last.png");this.___NZZZ.kZZ._zZZ(this,function(){if(this._HZZZ!==null){if(this._HZZZ._VZZZ===null&&this._HZZZ.___WZZ.___XZZ._N>0){this._HZZZ.Select(this._HZZZ.___WZZ.$ZZZZZ);}
else{this._HZZZ.Select(null);}}});this.___OZZZ.kZZ._zZZ(this,function(){if(this._HZZZ!==null){if(this._HZZZ.___WZZ.___XZZ._N>0){for(var O=0;O<5;O++){if(this._HZZZ._VZZZ!==null&&this._HZZZ._VZZZ._YZZZZ!==null){this._HZZZ.Select(this._HZZZ._VZZZ._YZZZZ);}
else if(this._HZZZ._VZZZ!==null&&this._HZZZ._VZZZ.____YZ!==this._HZZZ.___WZZ){this._HZZZ.Select(this._HZZZ._VZZZ.____YZ._PZZZZ);break;}
else{this._HZZZ.Select(null);break;}}}}});this.___PZZZ.kZZ._zZZ(this,function(){if(this._HZZZ!==null){if(this._HZZZ._VZZZ!==null&&this._HZZZ._VZZZ._YZZZZ!==null){this._HZZZ.Select(this._HZZZ._VZZZ._YZZZZ);}
else if(this._HZZZ._VZZZ!==null&&this._HZZZ._VZZZ.____YZ!==this._HZZZ.___WZZ){this._HZZZ.Select(this._HZZZ._VZZZ.____YZ._PZZZZ);}
else{this._HZZZ.Select(null);}}});this.___QZZZ.kZZ._zZZ(this,function(){if(this._HZZZ!==null){if(this._HZZZ._VZZZ===null){if(this._HZZZ.___WZZ.___XZZ._N>0){this._HZZZ.Select(this._HZZZ.___WZZ.$ZZZZZ);}}
else if(this._HZZZ._VZZZ._VZZZZ!==null){this._HZZZ.Select(this._HZZZ._VZZZ._VZZZZ);}}});this.___RZZZ.kZZ._zZZ(this,function(){if(this._HZZZ!==null){if(this._HZZZ._VZZZ===null){if(this._HZZZ.___WZZ.___XZZ._N>0){this._HZZZ.Select(this._HZZZ.___WZZ.$ZZZZZ);}}
if(this._HZZZ._VZZZ!==null){var O=0;while(O<5&&this._HZZZ._VZZZ._VZZZZ!==null){this._HZZZ.Select(this._HZZZ._VZZZ._VZZZZ);O++;}}}});this.___SZZZ.kZZ._zZZ(this,function(){if(this._HZZZ!==null){if(this._HZZZ.___WZZ.hZZZZZ!==null){this._HZZZ.Select(this._HZZZ.___WZZ.hZZZZZ);}}});}
cZZZZ.prototype.mZZ=function(){v._rZ(this.TZZ,{width:this.width});}