function ___UZZZ(parent){hZZ.iZZ(this,parent);____VZ.iZZ(this);this.$ZZ=new h(this);this.width=300;this.height=120;this.___VZZZ=1;this.___WZZZ="solid";this.___XZZZ="#a5a5a5";this.___pZZZ="#ffffff";this.padding=8;this.___YZZZ=12;this.cZZZ();this.nZZ();}
___UZZZ.prototype.cZZZ=function(){this.___ZZZZ=new lZZ(this,function(){return this.___YZZZ;},function(value){this.___YZZZ=value;this.mZZ();});this.___qZZZ=new lZZ(this,function(){return this.___pZZZ;},function(value){this.___pZZZ=value;this.mZZ();});this.__$ZZZZ=new lZZ(this,function(){return this.height;},function(value){this.height=value;this.mZZ();});this.RZZ=new lZZ(this,function(){return this.width;},function(value){this.width=value;this.mZZ();});this.__BZ=new lZZ(this,function(){return this.___VZZZ;},function(value){this.___VZZZ=value;this.mZZ();});this.__aZZZZ=new lZZ(this,function(){return this.___WZZZ;},function(value){this.___WZZZ=value;this.mZZ();});this.__bZZZZ=new lZZ(this,function(){return this.___XZZZ;},function(value){this.___XZZZ=value;this.mZZ();});this._KZZ=new lZZ(this,function(){return this.padding;},function(value){this.padding=value;this.mZZ();});}
___UZZZ.prototype.nZZ=function(){this.____IZZ=UZZ(this.pZZ);this.__cZZZZ=UZZ(this.____IZZ);this.__cZZZZ.appendChild(this.___WZZ.pZZ);v._rZ(this.____IZZ,{overflowY:"scroll"});this.___WZZ.nZZ();this.mZZ();}
___UZZZ.prototype.mZZ=function(){v._rZ(this.pZZ,{fontSize:this.___YZZZ,width:this.width,backgroundColor:this.___pZZZ});v._rZ(this.____IZZ,{height:this.height,borderWidth:this.___VZZZ,borderStyle:this.___WZZZ,borderColor:this.___XZZZ});v._rZ(this.__cZZZZ,{padding:this.padding});}
___UZZZ.prototype.Select=function(_UZZZ){____VZ.prototype.Select.call(this,_UZZZ);if(_UZZZ!==null){_UZZZ.Select();var _mZ=this.____IZZ;if(_UZZZ===this.___WZZ.hZZZZZ){_mZ.scrollTop=_mZ.scrollHeight;}
else{var __dZZZZ=_mZ.scrollTop;var __eZZZZ=_mZ.offsetHeight;var _kZ=v._iZ(_UZZZ.pZZ,_pZ)-v._iZ(_mZ,_pZ);var __fZZZZ=_UZZZ.__gZZZZ.__wZ();var __hZZZZ=_kZ+__fZZZZ;var __iZZZZ=__dZZZZ+__eZZZZ;if(__hZZZZ>__iZZZZ){_mZ.scrollTop=(_kZ-(__eZZZZ-__fZZZZ))+this.padding;}
else if(_kZ<__dZZZZ){_mZ.scrollTop=_kZ-this.padding;}}}}
___UZZZ.prototype.iZZZZZ=function(){if(this._VZZZ!==null){this._VZZZ._CZZ();}
____VZ.prototype.iZZZZZ.call(this);}
___UZZZ.prototype.____WZ=function(____XZ){return new __jZZZZ(this,____XZ);}