function __NZZZZ(parent){hZZ.iZZ(this,parent,true);this.width=2;this.height=7;this.__OZZZZ=null;this.__PZZZZ=null;this._____WZ=[];this.____vZZ=null;this.__WZZ=[];this.__WZZ.push(zZZZZ);this.__WZZ.push(null);this.__QZZZZ=1;var __RZZZZ=2;var FZZZZ,____BZ,____CZ;____BZ=0;____CZ=0;for(var FZZZZ=____lZ;FZZZZ<=____qZ;FZZZZ++){this.__SZZZZ(this.______V(____CZ,____BZ)+__RZZZZ,FZZZZ);____BZ++;}
____BZ=0;____CZ=1;for(var FZZZZ=____rZ;FZZZZ<=____wZ;FZZZZ++){this.__SZZZZ(this.______V(____CZ,____BZ)+__RZZZZ,FZZZZ);____BZ++;}
this._____YZ=new h(this);this._dZZZ={};this.____aZZ();this.border=["#686868"];this.____bZZ=30;this.____cZZ=null;this.piece_style=__n;this.__TZZZZ=new lZZ(this,function(){return this.____cZZ;},function(value){this.____cZZ=value;this.mZZ();});this.____dZZ=new lZZ(this,function(){return this.____bZZ;},function(value){this.____bZZ=value;this.mZZ();});this.__CZZ=new lZZ(this,function(){return this.piece_style;},function(value){this.piece_style=value;this.mZZ();});this.__UZZZZ=new lZZ(this,function(){return this.border;},function(value){this.border=value;this.nZZ();});this.__VZZZZ=new lZZ(this,function(){return this.__PZZZZ.checked;},function(value){this.__PZZZZ.checked=value;});this.nZZ();}
__NZZZZ.__WZZZZ=1;__NZZZZ.__XZZZZ=2;__NZZZZ.prototype.nZZ=function(){v._BZ(this.pZZ);var self=this;this._____WZ=[];this.__YZZZZ=_hZ("*div");this.pZZ.appendChild(this.__YZZZZ);var border;var parent=this.__YZZZZ;for(var O=0;O<this.border.length;O++){border=_hZ("*div");parent.appendChild(border);v._rZ(border,{border:"1px solid "+this.border[O]});parent=border;}
this.__SZZ=_hZ("*div");parent.appendChild(this.__SZZ);var _____yZ,____eZZ,____fZZ;for(var ____BZ=0;____BZ<this.height;____BZ++){for(var ____CZ=0;____CZ<this.width;____CZ++){____eZZ=_hZ("*div");____fZZ=_hZ("*div");this.__SZZ.appendChild(____eZZ);____eZZ.appendChild(____fZZ);v.w(____fZZ,"mousedown",function(r){self.____iZZ(r);});v.w(____fZZ,"mouseup",function(r){self.____jZZ(r);});_____yZ={FZZ:____eZZ,pZZ:____fZZ};this._____WZ.push(_____yZ);}}
var id=_.A();this.__OZZZZ=_hZ("*div");this.pZZ.appendChild(this.__OZZZZ);this.__PZZZZ=_hZ("*input");this.__OZZZZ.appendChild(this.__PZZZZ);this.__PZZZZ.setAttribute("type","checkbox");this.__PZZZZ.setAttribute("id",id);var qZZ=_hZ("*label");this.__OZZZZ.appendChild(qZZ);qZZ.setAttribute("for",id);qZZ.appendChild(_hZ("%Hold"));this.mZZ();v.w(v._gZ(),"mousemove",function(r){self.____kZZ(r);});}
__NZZZZ.prototype.mZZ=function(){var _kZ=v._qZ(this.pZZ);var __ZZZZZ=this.____CZZ();var _$ZZZZZ=this.____DZZ();v._rZ(this.__SZZ,{width:__ZZZZZ,height:_$ZZZZZ});v._rZ(this.pZZ,{width:(this.border.length*2)+__ZZZZZ,height:(this.border.length*2)+_$ZZZZZ+this.__OZZZZ.offsetHeight});v._rZ(this.__YZZZZ,{position:"absolute",top:_kZ[_pZ],left:_kZ[_oZ]});var _aZZZZZ=v._qZ(this.__SZZ);var _____yZ;for(var wZZZZ=0;wZZZZ<this._____WZ.length;wZZZZ++){_____yZ=this._____WZ[wZZZZ];v._rZ(_____yZ.FZZ,{position:"absolute",width:this.____bZZ,height:this.____bZZ});this.____mZZ(_____yZ,wZZZZ);v._rZ(_____yZ.pZZ,{position:"absolute",width:this.____bZZ,height:this.____bZZ});}
this._bZZZZZ();v._rZ(this.__OZZZZ,{position:"absolute",top:_kZ[_pZ]+(this.pZZ.offsetHeight-this.__OZZZZ.offsetHeight),left:_kZ[_oZ],padding:0});}
__NZZZZ.prototype.DZZZZ=function(wZZZZ,FZZZZ){this.__SZZZZ(wZZZZ,FZZZZ);this._cZZZZZ(wZZZZ,FZZZZ);}
__NZZZZ.prototype.__SZZZZ=function(wZZZZ,FZZZZ){this.__WZZ[wZZZZ]=FZZZZ;}
__NZZZZ.prototype._cZZZZZ=function(wZZZZ,FZZZZ){if(this.EZZZZ(wZZZZ)!==null){if(this.____cZZ!==null){this._____WZ[wZZZZ].pZZ.style.backgroundImage=_.a.___YZ(this.____cZZ+"/"+this.piece_style+"/"+this.____bZZ+"/"+_WZZZ.____yZ(FZZZZ)+".png");}}}
__NZZZZ.prototype._bZZZZZ=function(){for(var wZZZZ=0;wZZZZ<this.__WZZ.length;wZZZZ++){this._cZZZZZ(wZZZZ,this.__WZZ[wZZZZ]);}}
__NZZZZ.prototype.EZZZZ=function(wZZZZ){return this.__WZZ[wZZZZ];}
__NZZZZ.prototype.____CZZ=function(){return this.____bZZ*this.width;}
__NZZZZ.prototype.____DZZ=function(){return this.____bZZ*this.height;}
__NZZZZ.prototype.__PZ=function(wZZZZ){return(wZZZZ%this.width);}
__NZZZZ.prototype.__QZ=function(wZZZZ){return((wZZZZ-this.__PZ(wZZZZ))/this.width);}
__NZZZZ.prototype.____mZZ=function(_____yZ,wZZZZ){var __PZ,__QZ;var ____BZ=this.__QZ(wZZZZ);var ____CZ=this.__PZ(wZZZZ);__PZ=this.____bZZ*____CZ;__QZ=this.____bZZ*((this.height-1)-____BZ);v._rZ(_____yZ.FZZ,{top:this.border.length+__QZ,left:this.border.length+__PZ});}
__NZZZZ.prototype.____nZZ=function(_____yZ){v._rZ(_____yZ.pZZ,{top:0,left:0});}
__NZZZZ.prototype.____oZZ=function(_____yZ,__PZ,__QZ){var _kZ=v._qZ(_____yZ.FZZ);v._rZ(_____yZ.pZZ,{top:__QZ-_kZ[_pZ],left:__PZ-_kZ[_oZ]});}
__NZZZZ.prototype._dZZZZZ=function(r){var _kZ=v._qZ(this.__SZZ);return this._eZZZZZ(r.pageX-_kZ[_oZ],this.____DZZ()-(r.pageY-_kZ[_pZ]));}
__NZZZZ.prototype._eZZZZZ=function(__PZ,__QZ){var ____CZ=(__PZ-(__PZ%this.____bZZ))/this.____bZZ;var ____BZ=(__QZ-(__QZ%this.____bZZ))/this.____bZZ;return this.______V(____CZ,____BZ);}
__NZZZZ.prototype.____aZZ=function(){this._dZZZ={____pZZ:false,____qZZ:null,_qZZ:false,____rZZ:false,____sZZ:false,_aZZZ:null,_mZZZ:null,____tZZ:0,____uZZ:0};this.____vZZ=null;}
__NZZZZ.prototype.____iZZ=function(r){r.preventDefault();if(this.____wZZ(r)){var wZZZZ=this._dZZZZZ(r);var _____yZ=this._____WZ[wZZZZ];var _kZ=v._qZ(_____yZ.FZZ);if(wZZZZ!==this.__QZZZZ){this.____xZZ(_____yZ);if(!this._dZZZ._qZZ){this._dZZZ._qZZ=true;this._dZZZ.____pZZ=true;this._dZZZ._mZZZ=wZZZZ;this._dZZZ._aZZZ=this.__WZZ[wZZZZ];this._dZZZ.____tZZ=r.pageX-_kZ[_oZ];this._dZZZ.____uZZ=r.pageY-_kZ[_pZ];}}}}
__NZZZZ.prototype.____kZZ=function(r){r.preventDefault();if(this._dZZZ.____pZZ){this._dZZZ.____sZZ=true;}
if(this._dZZZ._qZZ&&this._dZZZ.____sZZ){this.____oZZ(this._____WZ[this._dZZZ._mZZZ],r.pageX-this._dZZZ.____tZZ,r.pageY-this._dZZZ.____uZZ);}}
__NZZZZ.prototype.____jZZ=function(r){r.preventDefault();var wZZZZ=this._dZZZZZ(r);var ____yZZ=this._____WZ[this._dZZZ._mZZZ];this._dZZZ.____pZZ=false;this.____vZZ=null;if(this._dZZZ.____sZZ){if(!this.____wZZ(r)){this._____YZ.t({_aZZZ:this.__WZZ[this._dZZZ._mZZZ],h:r,_dZZZ:this._dZZZ});}
this.____nZZ(____yZZ);this.____aZZ();this.____zZZ(____yZZ);}
else if(wZZZZ!==this.__QZZZZ){if(this._dZZZ.____rZZ&&wZZZZ==this._dZZZ._mZZZ){this.____FZZ(this._dZZZ._mZZZ);this.____aZZ();}
else{this.____FZZ(this._dZZZ._mZZZ);this._dZZZ.____rZZ=true;this.____EZZ(wZZZZ);this._dZZZ._mZZZ=wZZZZ;this._dZZZ._aZZZ=this.__WZZ[wZZZZ];this.____vZZ=this.__WZZ[wZZZZ];}}}
__NZZZZ.prototype.____xZZ=function(_____yZ){v._rZ(_____yZ.pZZ,{zIndex:_fZZZ.____AZZ});}
__NZZZZ.prototype.____zZZ=function(_____yZ){v._rZ(_____yZ.pZZ,{zIndex:_fZZZ.____BZZ});}
__NZZZZ.prototype.____wZZ=function(r){var __PZ=r.pageX;var __QZ=r.pageY;var _kZ=v._qZ(this.__SZZ);var top=_kZ[_pZ]+1;var right=_kZ[_oZ]+this.____CZZ()-1;var bottom=_kZ[_pZ]+this.____DZZ()-1;var left=_kZ[_oZ]+1;return!(__PZ<left||__PZ>right||__QZ<top||__QZ>bottom);}
__NZZZZ.prototype.____EZZ=function(wZZZZ){v._rZ(this._____WZ[wZZZZ].FZZ,{backgroundColor:"#808080"});}
__NZZZZ.prototype.____FZZ=function(wZZZZ){v._rZ(this._____WZ[wZZZZ].FZZ,{backgroundColor:"inherit"});}
__NZZZZ.prototype.______V=function(____CZ,____BZ){return(____BZ*this.width+____CZ);}
__NZZZZ.prototype._CZZ=function(){if(this._dZZZ.____rZZ){this.____FZZ(this._dZZZ._mZZZ);this.____aZZ();}}