function _DZZZZZ(parent,game_id,_EZZZZZ){hZZ.iZZ(this,parent);this._EZZZZZ=_EZZZZZ||false;this.username=null;this.rating=0;this.jZZZZ=0;this._FZZZZZ=false;this._GZZZZZ=false;this.colour=_____d;this.game_id=game_id;this.height=26;this._pZZZZZ=4;this._HZZZZZ="/img/icon/colour_dot";this.___YZZZ=16;this.___UZ=new lZZ(this,function(){return this.game_id;},function(value){this.game_id=value;});;this.___ZZZZ=new lZZ(this,function(){return this.___YZZZ;},function(value){this.___YZZZ=value;this.mZZ();});this._IZZZZZ=new lZZ(this,function(){return this._HZZZZZ;},function(value){this._HZZZZZ=value;this.mZZ();});this.__$ZZZZ=new lZZ(this,function(){return this.height;},function(value){this.height=value;this.mZZ();});this._rZZZZZ=new lZZ(this,function(){return this._pZZZZZ;},function(value){this._pZZZZZ=value;this.mZZ();});this._JZZZZZ=new h(this);this.___VZ=new lZZ(this,function(){return this.colour;},function(value){this.colour=value;this.mZZ();});this.__pZZ=new lZZ(this,function(){return this.username;},function(value){if(value!==this.username){this.username=value;this._GZZZZZ=false;this.mZZ();}});this._KZZZZZ=new lZZ(this,function(){return this.rating;},function(value){if(value!==null&&value>0){this.rating=value;this._GZZZZZ=true;}
else{this.rating=null;this._GZZZZZ=false;}
this.mZZ();});this._LZZZZZ=new lZZ(this,function(){return this.jZZZZ;},function(value){this.jZZZZ=value;this.mZZ();});this._MZZZZZ=new lZZ(this,function(){return this._FZZZZZ;},function(value){this._FZZZZZ=value;this.mZZ();});this.nZZ();}
_DZZZZZ.prototype.nZZ=function(){var self=this;this.TZZ=UZZ(this.pZZ);this._NZZZZZ=UZZ(this.TZZ);this._OZZZZZ=UZZ(this.TZZ);this._PZZZZZ=_hZ("*img");this._NZZZZZ.appendChild(this._PZZZZZ);this._QZZZZZ=new Button(this._NZZZZZ,"Sit");this._QZZZZZ.kZZ._zZZ(this,function(){this._JZZZZZ.t();});this._RZZZZZ=_hZ("*span");this._OZZZZZ.appendChild(this._RZZZZZ);this._RZZZZZ.target="_blank";this._SZZZZZ=_hZ("*span");this._OZZZZZ.appendChild(this._SZZZZZ);this._TZZZZZ=_hZ("*span");this._OZZZZZ.appendChild(this._TZZZZZ);this.mZZ();}
_DZZZZZ.prototype.mZZ=function(){v._rZ(this.pZZ,{height:this.height});v._rZ(this._NZZZZZ,{display:"none"});v._rZ(this._OZZZZZ,{display:"none"});if(this.username===null&&this._EZZZZZ){v._rZ(this._NZZZZZ,{display:""});this._PZZZZZ.src=G(this._HZZZZZ+"/"+_$ZZZ.______X(this.colour)+".png");v._rZ(this._PZZZZZ,{verticalAlign:"middle",marginRight:8});}
else if(this.username!==null){v._rZ(this._OZZZZZ,{display:""});v._rZ(this._OZZZZZ,{paddingTop:this._pZZZZZ});v._rZ(this._RZZZZZ,{fontSize:this.___YZZZ,color:"#343434"});this._RZZZZZ.innerHTML=this.username;if(this._GZZZZZ){this._SZZZZZ.innerHTML=" ("+this.rating+")";}
else{this._SZZZZZ.innerHTML="";}
if(this._FZZZZZ){this._TZZZZZ.innerHTML=" ["+this.jZZZZ.toFixed(1)+"]";}
else{this._TZZZZZ.innerHTML="";}}}
_DZZZZZ.prototype._UZZZZZ=function(type,variant,format){if(this.username!==null){____v.____w(G("/xhr/get_rating.php"),function(____x){var data=o.p(____x);if(data===false){this._KZZZZZ.BZZ(null);}
else{this._KZZZZZ.BZZ(data);}},{"q":o.I({"user":this.username,"type":type,"variant":variant,"format":format})},this);}}