function qZZZZZZ(parent){hZZ.iZZ(this,parent);this.width=300;this.padding=0;this.rZZZZZZ="#E4F2CB";this.sZZZZZZ="#e4e4e4";this.tZZZZZZ=this.rZZZZZZ;this.variant=_aZ;this.timing_initial=600;this.timing_increment=15;this.uZZZZZZ="-200";this.vZZZZZZ="+200";this.rated=true;this.choose_colour=false;this.challenge_colour=_____d;this.challenge_to=null;this.wZZZZZZ=new h(this);this.___aZZZ=null;this.xZZZZZZ=new lZZ(this,function(){return(this.___aZZZ!==null&&this.___aZZZ.yZZZZZZ.__wZ());});this.RZZ=new lZZ(this,function(){return this.width;},function(value){this.width=value;this.mZZ();});this._KZZ=new lZZ(this,function(){return this.padding;},function(value){this.padding=value;this.mZZ();});this.___hZZ=new lZZ(this,function(){return this.variant;},function(value){this.variant=value;this.zZZZZZZ();});this.___tZZ=new lZZ(this,function(){return this.timing_initial;},function(value){this.timing_initial=value;this.zZZZZZZ();});this.___uZZ=new lZZ(this,function(){return this.timing_increment;},function(value){this.timing_increment=value;this.zZZZZZZ();});this.AZZZZZZ=new lZZ(this,function(){return this.uZZZZZZ;},function(value){this.uZZZZZZ=value;this.zZZZZZZ();});this.BZZZZZZ=new lZZ(this,function(){return this.vZZZZZZ;},function(value){this.vZZZZZZ=value;this.zZZZZZZ();});this.___GZZ=new lZZ(this,function(){return this.rated;},function(value){this.rated=value;this.zZZZZZZ();});this.CZZZZZZ=new lZZ(this,function(){return this.choose_colour;},function(value){this.choose_colour=value;this.zZZZZZZ();});this.DZZZZZZ=new lZZ(this,function(){return this.challenge_colour;},function(value){this.challenge_colour=value;this.zZZZZZZ();});this.EZZZZZZ=new lZZ(this,function(){return this.challenge_to;},function(value){this.challenge_to=value;this.mZZ();});this.nZZ();}
qZZZZZZ.prototype.nZZ=function(){var self=this;this.__JZ=UZZ(this.pZZ);this.FZZZZZZ=_hZ("*form");this.FZZZZZZ._jZZZZ="#";this.__JZ.appendChild(this.FZZZZZZ);this.____IZZ=UZZ(this.FZZZZZZ);var __kZ,_KZZZ;var _WZZZZZ="100%";v._rZ(this.____IZZ,{fontSize:11});__kZ=UZZ(this.____IZZ);_KZZZ=new ___J(__kZ,{___L:_WZZZZZ,___M:55,___N:145,___Q:___Z});_KZZZ.tZZ.Text.BZZ("Variant");var options=[];for(var code in _bZ[jZ]){options.push({NZZ:code,tZZ:_bZ[jZ][code]._fZ});}
this.GZZZZZZ=new __dZ(_KZZZ.___W,options);this.GZZZZZZ.NZZ.BZZ(_aZ);this.GZZZZZZ.LZZ._zZZ(this,function(data,sender){this.variant=sender.NZZ.__wZ();});__kZ=UZZ(this.____IZZ);_KZZZ=new ___J(__kZ,{___L:_WZZZZZ,___M:100,___N:100,___Q:___Z});_KZZZ.tZZ.Text.BZZ("Time control");this.HZZZZZZ=new JZZ(_KZZZ.___W);this.HZZZZZZ._P(null,"Custom");this.HZZZZZZ.NZZ.BZZ(null);for(var O=0;O<______t.length;O++){if(______t[O]._rZ===__I){this.HZZZZZZ._P(O,______t[O]._fZ);}}
this.HZZZZZZ.LZZ._zZZ(this,function(data,sender){if(data.YZZ!==null){this.___tZZ.BZZ(______t[data.YZZ].______u);this.___uZZ.BZZ(______t[data.YZZ].______v);}});__kZ=UZZ(this.____IZZ);_KZZZ=new ___J(__kZ,{___L:_WZZZZZ,___M:100,___N:100,___Q:___Z});_KZZZ.tZZ.Text.BZZ("Initial time");this.IZZZZZZ=new _aZZ(_KZZZ.___W);this.IZZZZZZ.RZZ.BZZ(90);this.IZZZZZZ.___l.BZZ("Accepts units, e.g. '1d'.  Default units are minutes.");this.IZZZZZZ._bZZ._zZZ(this,function(data,sender){this.timing_initial=____eZ.TZZZZZ(data.YZZ,"m");this.HZZZZZZ.NZZ.BZZ(null);});__kZ=UZZ(this.____IZZ);_KZZZ=new ___J(__kZ,{___L:_WZZZZZ,___M:100,___N:100,___Q:___Z});_KZZZ.tZZ.Text.BZZ("Increment");this.JZZZZZZ=new _aZZ(_KZZZ.___W);this.JZZZZZZ.RZZ.BZZ(90);this.JZZZZZZ.___l.BZZ("Accepts units, e.g. '3m30'.  Default units are seconds.");this.JZZZZZZ._bZZ._zZZ(this,function(data,sender){this.timing_increment=____eZ.TZZZZZ(data.YZZ,"s");this.HZZZZZZ.NZZ.BZZ(null);});this.KZZZZZZ=new FZZ(this.____IZZ);__kZ=UZZ(this.KZZZZZZ.pZZ);_KZZZ=new ___J(__kZ,{___L:_WZZZZZ,___M:100,___N:100,___Q:___Z});_KZZZ.tZZ.Text.BZZ("Rating min.");this.LZZZZZZ=new _aZZ(_KZZZ.___W);this.LZZZZZZ.RZZ.BZZ(50);this.LZZZZZZ.___l.BZZ("Enter an absolute value, or prefix with '+' or '-' to base it on your rating");this.LZZZZZZ._bZZ._zZZ(this,function(data,sender){this.uZZZZZZ=data.YZZ;});__kZ=UZZ(this.KZZZZZZ.pZZ);_KZZZ=new ___J(__kZ,{___L:_WZZZZZ,___M:100,___N:100,___Q:___Z});_KZZZ.tZZ.Text.BZZ("Rating max.");this.MZZZZZZ=new _aZZ(_KZZZ.___W);this.MZZZZZZ.RZZ.BZZ(50);this.LZZZZZZ.___l.BZZ("Enter an absolute value, or prefix with '+' or '-' to base it on your rating");this.MZZZZZZ._bZZ._zZZ(this,function(data,sender){this.vZZZZZZ=data.YZZ;});__kZ=UZZ(this.____IZZ);_KZZZ=new ___J(__kZ,{___L:_WZZZZZ,___M:180,___N:20,___Q:___Z});this.__zZZZZ=new Checkbox(_KZZZ.___W);_KZZZ.tZZ.Text.BZZ("Rated\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0");_KZZZ.tZZ.___I.BZZ(this.__zZZZZ.sZZ);this.__zZZZZ.rZZ._zZZ(this,function(data,sender){this.rated=sender.uZZ.__wZ();if(this.rated){this.choose_colour=false;}
this.zZZZZZZ();});__kZ=UZZ(this.____IZZ);_KZZZ=new ___J(__kZ,{___L:_WZZZZZ,___M:60,___N:140,___Q:___Z});this.NZZZZZZ=new __dZ(_KZZZ.___W,[{NZZ:null,tZZ:"Any"},{NZZ:_____d,tZZ:"White"},{NZZ:kZZZZ,tZZ:"Black"}]);_KZZZ.tZZ.Text.BZZ("Colour");this.NZZZZZZ.LZZ._zZZ(this,function(data,sender){var value=sender.NZZ.__wZ();if(value===null){this.choose_colour=false;}
else{this.choose_colour=true;this.rated=false;this.challenge_colour=value;}
this.zZZZZZZ();});this.OZZZZZZ=new FZZ(this.____IZZ);v._rZ(this.OZZZZZZ.pZZ,{paddingTop:4});this.PZZZZZZ=UZZ(this.OZZZZZZ.pZZ);v._rZ(this.PZZZZZZ,{padding:4,borderRadius:3});this.___hZZZ=wZZ(this.PZZZZZZ);this.QZZZZZZ=_hZ("*img");this.___hZZZ.appendChild(this.QZZZZZZ);this.QZZZZZZ.src=_.a.rZZZ("/loading.gif");v._rZ(this.QZZZZZZ,{verticalAlign:"middle",marginRight:5});this.RZZZZZZ=new tZZ(this.___hZZZ);__kZ=UZZ(this.____IZZ);v._rZ(__kZ,{paddingTop:5});_KZZZ=new ___J(__kZ,{___L:_WZZZZZ,___M:50,___N:150,___Q:___Z});this.SZZZZZZ=new Button(_KZZZ.___W,"Start game");this.SZZZZZZ.oZZ.type="submit";v.w(this.FZZZZZZ,"submit",function(r){if(___w(r.preventDefault)){r.preventDefault();}
if(self.___aZZZ!==null&&self.___aZZZ.yZZZZZZ.__wZ()){self._bZZZ();}
else{self.Submit();}
return false;});this.mZZ();}
qZZZZZZ.prototype.mZZ=function(){v._rZ(this.__JZ,{width:this.width});v._rZ(this.____IZZ,{padding:this.padding});v._rZ(this.PZZZZZZ,{backgroundColor:this.tZZZZZZ});var TZZZZZZ=(this.___aZZZ!==null&&this.___aZZZ.yZZZZZZ.__wZ());this.SZZZZZZ.Text.BZZ(TZZZZZZ?"Cancel":"Start game");v._rZ(this.QZZZZZZ,{display:TZZZZZZ?"":"none"});if(this.challenge_to===null){this.KZZZZZZ.EZZ();}
else{this.KZZZZZZ.DZZ();}
this.zZZZZZZ();}
qZZZZZZ.prototype.gZZZZZZ=function(){this.___aZZZ=null;this.HZZZZZZ.NZZ.BZZ(null);this.SZZZZZZ.___B.BZZ(true);this.OZZZZZZ.DZZ();this.mZZ();this.IZZZZZZ.___G();this.IZZZZZZ.Select();}
qZZZZZZ.prototype.zZZZZZZ=function(){this.IZZZZZZ.NZZ.BZZ(____eZ.____$Z(this.timing_initial,false,"m"));this.JZZZZZZ.NZZ.BZZ(____eZ.____$Z(this.timing_increment,false,"s"));this.LZZZZZZ.NZZ.BZZ(this.uZZZZZZ);this.MZZZZZZ.NZZ.BZZ(this.vZZZZZZ);this.__zZZZZ.uZZ.BZZ(this.rated);if(this.choose_colour){this.NZZZZZZ.NZZ.BZZ(this.challenge_colour);}
else{this.NZZZZZZ.NZZ.BZZ(null);}}
qZZZZZZ.prototype.Submit=function(){var self=this;var UZZZZZZ=false;if(this.timing_initial<1){alert("Initial time must be more than 0");UZZZZZZ=true;this.IZZZZZZ.___G();}
if(!UZZZZZZ){this.___aZZZ=new ___aZZZ(this.variant,this.timing_initial,this.timing_increment,this.uZZZZZZ,this.vZZZZZZ,this.rated,this.choose_colour,this.challenge_colour,this.challenge_to);this.___aZZZ.Submit();this.OZZZZZZ.EZZ();this.tZZZZZZ=this.rZZZZZZ;this.RZZZZZZ.Text.BZZ("Waiting for opponent...");this.mZZ();this.___aZZZ.wZZZZZZ._zZZ(this,function(data){if(data.VZZZZZZ===___aZZZ.WZZZZZZ){this.tZZZZZZ=this.sZZZZZZ;if(this.___aZZZ.EZZZZZZ===null){this.RZZZZZZ.Text.BZZ("No matching opponents found.");}
else{this.RZZZZZZ.Text.BZZ(this.challenge_to+" declined your challenge.");}}
this.wZZZZZZ.t(data);this.mZZ();});}}
qZZZZZZ.prototype._bZZZ=function(){this.OZZZZZZ.DZZ();if(this.___aZZZ!==null){this.___aZZZ._bZZZ();}
this.mZZ();}