function _fZZZ(parent){__WZZ.iZZ(this);hZZ.iZZ(this,parent,true);this.______jZ=[];this.______kZ=[];this._____WZ=[];this.______lZ=null;this.______mZ=null;this._lZZZ=new h(this);this.______nZ=new h(this);this.______oZ=new h(this);this.______pZ=new h(this);this.______qZ=new h(this);this.______rZ=new h(this);this.__XZZ=new h(this);this._cZZZ=new h(this);this._jZZZ=new h(this);this.______sZ=new h(this);this.______tZ=new h(this);this.______uZ=new h(this);this.______vZ=new h(this);this.______wZ();this.______xZ=[];this.______yZ=null;this.______zZ=null;this.______AZ=null;this.______BZ=null;this.______CZ=null;this._____ZZ=_fZZZ._gZZZ|_fZZZ.____$ZZ;this._dZZZ={};this.____aZZ();this.______DZ=1;this.border=["#5f5f5f","#5f5f5f"];this.______EZ=true;this.show_coords=_.a.___GZ.___QZ.__FZZ.__wZ();this.______FZ=18;this.______GZ=18;this.______HZ="sans-serif";this.______IZ=11;this.______JZ="#303030";this.____bZZ=_.a.___GZ.___QZ.__EZZ.__wZ();this.______KZ=_____d;this.______LZ="/board/board";this.____cZZ="/board/piece";this.board_style=null;this.piece_style=_.a.___GZ.___QZ.__CZZ.__wZ();this.______MZ=_.a.___GZ.___QZ.__KZZ.__wZ();this.______NZ=0;this.______OZ=true;this.______PZ=true;this.______QZ="#efefef";this.______RZ=true;this.______SZ=1;this.______TZ="#dfdfdf";_.a.___GZ.___QZ.__wZZ._zZZ(this,function(data,sender){this.__CZZ.BZZ(sender.__CZZ.__wZ());});_.a.___GZ.___QZ.__yZZ._zZZ(this,function(data,sender){this.______MZ=sender.__KZZ.__wZ();this.mZZ();});_.a.___GZ.___QZ.__zZZ._zZZ(this,function(data,sender){this.____dZZ.BZZ(sender.__EZZ.__wZ());});_.a.___GZ.___QZ.__AZZ._zZZ(this,function(data,sender){this.__FZZ.BZZ(sender.__FZZ.__wZ());});this.cZZZ();this.nZZ();}
_fZZZ.____AZZ=5;_fZZZ.____BZZ=4;_fZZZ.______UZ=2;_fZZZ.______VZ=1;_fZZZ._gZZZ=2;_fZZZ.____$ZZ=4;_fZZZ.prototype.______wZ=function(){this.______WZ={visibility:"hidden"};this.______XZ={visibility:"inherit",backgroundColor:"#99e457",backgroundImage:"none",opacity:".9"};this.______YZ={visibility:"inherit",backgroundColor:"#62c1fe",opacity:".5"};this.______ZZ={visibility:"inherit",backgroundColor:"#62c1fe",opacity:".8"};this._____$ZZ={visibility:"inherit",backgroundColor:"#199a65",backgroundImage:"none",opacity:".9"};this._____aZZ={visibility:"inherit",backgroundColor:"#199a65",backgroundImage:"none",opacity:".9"};this._____bZZ={visibility:"inherit",backgroundColor:"#fbfddd",backgroundImage:"none",opacity:".9"};this._____cZZ={visibility:"inherit",backgroundColor:"#fbfddd",backgroundImage:"none",opacity:".9"};this._____dZZ={visibility:"inherit",backgroundColor:"#C9F06B",opacity:".8"};}
_fZZZ.prototype.cZZZ=function(){this._____eZZ=new lZZ(this,function(){return this.______OZ;},function(value){this.______OZ=value;if(value===true){this._bZZZZZ();}});this._____fZZ=new lZZ(this,function(){return this.______MZ;},function(value){if(this.______MZ!==value){this.______MZ=value;this.mZZ();}});this._____gZZ=new lZZ(this,function(){return this.______IZ;},function(value){if(this.______IZ!==value){this.______IZ=value;this.mZZ();}});this._____hZZ=new lZZ(this,function(){return this.______HZ;},function(value){if(this.______HZ!==value){this.______HZ=value;this.mZZ();}});this._____iZZ=new lZZ(this,function(){return this.______JZ;},function(value){if(this.______JZ!==value){this.______JZ=value;this.mZZ();}});this._____jZZ=new lZZ(this,function(){return this.______LZ;},function(value){if(this.______LZ!==value){this.______LZ=value;this.mZZ();}});this.__TZZZZ=new lZZ(this,function(){return this.____cZZ;},function(value){if(this.____cZZ!==value){this.____cZZ=value;this._uZZZ.__TZZZZ.BZZ(value);this.mZZ();}});this._QZZZ=new lZZ(this,function(){return this.______KZ;},function(value){if(this.______KZ!==value){this.______KZ=value;this.mZZ();}});this._____kZZ=new lZZ(this,function(){return this.______GZ;},function(value){if(this.______GZ!==value){this.______GZ=value;this.mZZ();this.fZZ.t();}});this._____lZZ=new lZZ(this,function(){return this.______FZ;},function(value){if(this.______FZ!==value){this.______FZ=value;this.mZZ();this.fZZ.t();}});this._____mZZ=new lZZ(this,function(){return this.______EZ;},function(value){if(this.______EZ!==value){this.______EZ=value;this.mZZ();this.fZZ.t();}});this.__FZZ=new lZZ(this,function(){return this.show_coords;},function(value){if(this.show_coords!==value){this.show_coords=value;if(this.show_coords){this._____mZZ.BZZ(true);}
this.mZZ();}});this.____dZZ=new lZZ(this,function(){return this.____bZZ;},function(value){if(this.____bZZ!==value){this.____bZZ=parseInt(value);this._uZZZ.____dZZ.BZZ(value);this.mZZ();this.fZZ.t();}});this._____nZZ=new lZZ(this,function(){return this.board_style;},function(value){if(this.board_style!==value){this.board_style=value;this.mZZ();}});this.__CZZ=new lZZ(this,function(){return this.piece_style;},function(value){if(this.piece_style!==value){this.piece_style=value;this._uZZZ.__CZZ.BZZ(value);this.mZZ();}});this.__UZZZZ=new lZZ(this,function(){return this.border;},function(value){this.board_style=value;this.mZZ();this.fZZ.t();});this._____oZZ=new lZZ(this,function(){return this.______NZ;},function(value){if(this.board_style!==value){this.board_style=value;this.mZZ();}});this._OZZZ=new lZZ(this,function(){return this.______PZ;},function(value){if(this.______PZ!==value){this.______PZ=value;this.mZZ();}});this._____pZZ=new lZZ(this,function(){return this.______QZ;},function(value){if(this.______QZ!==value){this.______QZ=value;this.mZZ();}});this._____qZZ=new lZZ(this,function(){return this.______RZ;},function(value){if(this.______RZ!==value){this.______RZ=value;this.mZZ();}});this._____rZZ=new lZZ(this,function(){return this.______SZ;},function(value){if(this.______SZ!==value){this.______SZ=value;this.mZZ();}});this._____sZZ=new lZZ(this,function(){return this.______TZ;},function(value){if(this.______TZ!==value){this.______TZ=value;this.mZZ();}});this.___L=new lZZ(this,function(){return this._____tZZ(_oZ);});this._____uZZ=new lZZ(this,function(){return this._____tZZ(_pZ);});}
_fZZZ.prototype.nZZ=function(){v._BZ(this.pZZ);var self=this;this.______jZ=[];this.______kZ=[];this._____WZ=[];this.____IZZ=UZZ(this.pZZ);v._rZ(this.____IZZ,{position:"absolute"});this._______v=UZZ(this.____IZZ);v._rZ(this._______v,{position:"absolute",zIndex:0});this.__YZZZZ=UZZ(this.____IZZ);v._rZ(this.__YZZZZ,{position:"absolute",zIndex:1});this.__SZZ=UZZ(this.__YZZZZ);v.w(this.__SZZ,"mouseout",function(r){self._____vZZ(r);});var _____fZ,_____wZZ,_____xZZ;for(var O=0;O<8;O++){_____wZZ=UZZ(this.____IZZ);_____xZZ=UZZ(_____wZZ);_____fZ={FZZ:_____wZZ,pZZ:_____xZZ};this.______kZ.push(_____fZ);}
for(var O=0;O<8;O++){_____wZZ=UZZ(this.____IZZ);_____xZZ=UZZ(_____wZZ);_____fZ={FZZ:_____wZZ,pZZ:_____xZZ};this.______jZ.push(_____fZ);}
var _____yZ,____eZZ,____fZZ,_____yZZ;for(var ____BZ=0;____BZ<8;____BZ++){for(var ____CZ=0;____CZ<8;____CZ++){____eZZ=UZZ(this.__SZZ);_____yZZ=UZZ(____eZZ);____fZZ=UZZ(____eZZ);v._rZ(____eZZ,{position:"absolute"});v._rZ(____fZZ,{position:"absolute",zIndex:_fZZZ.____BZZ});v._rZ(_____yZZ,{position:"absolute",zIndex:_fZZZ.______UZ,borderStyle:"solid",borderColor:"transparent",visibility:"hidden"});v.w(____fZZ,"mousedown",function(r){self.____iZZ(r);});v.w(____fZZ,"mouseup",function(r){self.____jZZ(r);});_____yZ={FZZ:____eZZ,pZZ:____fZZ,_____zZZ:_$ZZZ.______V(____CZ,____BZ),_____AZZ:_____yZZ};this._____WZ.push(_____yZ);}}
v.w(window,"mousemove",function(r){self.____kZZ(r);});this._uZZZ=new _uZZZ(this.__SZZ);this._uZZZ.___fZZZ.BZZ(_fZZZ.____AZZ);this._uZZZ.__TZZZZ.BZZ(this.____cZZ);this._uZZZ.__CZZ.BZZ(this.piece_style);this._uZZZ.____dZZ.BZZ(this.____bZZ);this.___vZZZ=new ___vZZZ(this.__SZZ);this.___vZZZ.___fZZZ.BZZ(_fZZZ.____AZZ);this.___dZZZ=new ___dZZZ(this.__SZZ);this.___dZZZ.___fZZZ.BZZ(_fZZZ.____AZZ);this.mZZ();}
_fZZZ.prototype.mZZ=function(){var _____BZZ,_____CZZ,gZZ;var board_size=this._____DZZ();var ______FZ=this._____lZZ.__wZ();var ______GZ=this._____kZZ.__wZ();var _____EZZ=this.______EZ?______FZ:0;var _____FZZ=this.______EZ?______GZ:0;var _____GZZ=this.______PZ?______FZ:_____EZZ;var _____HZZ=this.______PZ?______GZ:_____FZZ;var _____IZZ=this.______EZ?"":"none";var _____JZZ=this.show_coords?"":"hidden";v._rZ(this.pZZ,{paddingTop:this.______PZ?______GZ:0,paddingRight:this.______PZ?______FZ:0,borderWidth:this.______PZ?this.______SZ:0,borderColor:this.______TZ,borderStyle:"solid",backgroundColor:this.______PZ?this.______QZ:"inherit"});v._BZ(this._______v);var border;var _____KZZ=this._______v;for(var O=0;O<this.border.length;O++){border=UZZ(_____KZZ);v._rZ(border,{border:"1px solid "+this.border[O]});_____KZZ=border;}
v._rZ(_____KZZ,{width:board_size,height:board_size});for(var O=0;O<8;O++){v._rZ(this.______kZ[O].FZZ,{position:"absolute",top:this.border.length+(this.____bZZ*O),left:0,height:this.____bZZ,width:_____EZZ,display:_____IZZ,visibility:_____JZZ,cursor:"default"});v._rZ(this.______jZ[O].FZZ,{position:"absolute",top:(this.border.length*2)+board_size,left:______FZ+this.border.length+(this.____bZZ*O),width:this.____bZZ,height:_____FZZ,display:_____IZZ,visibility:_____JZZ,cursor:"default"});if(this.______KZ==_____d){_____BZZ=7-O;_____CZZ=O;}
else{_____BZZ=O;_____CZZ=7-O;}
v._BZ(this.______kZ[O].pZZ);gZZ=_hZ("%"+____EZ.charAt(_____BZZ));this.______kZ[O].pZZ.appendChild(gZZ);v._rZ(this.______kZ[O].pZZ,{marginTop:Math.round((this.____bZZ/2)-(this.______IZ/2))-this.______DZ});v._BZ(this.______jZ[O].pZZ);gZZ=_hZ("%"+_____P.charAt(_____CZZ));this.______jZ[O].pZZ.appendChild(gZZ);v._rZ(this.______jZ[O].pZZ,{fontFamily:this.______HZ,fontSize:this.______IZ,fontWeight:"normal",color:this.______JZ,lineHeight:_____FZZ,textAlign:"center"});v._rZ(this.______kZ[O].pZZ,{fontFamily:this.______HZ,fontSize:this.______IZ,color:this.______JZ,fontWeight:"normal",textAlign:"center"});}
v._rZ(this.pZZ,{width:_____GZZ+(this.border.length*2)+board_size,height:_____HZZ+(this.border.length*2)+board_size});v._rZ(this._______v,{top:0,left:_____GZZ});v._rZ(this.__YZZZZ,{top:this.border.length,left:_____GZZ+this.border.length,width:board_size,height:board_size});var _____LZZ="none";if(this.board_style!==null){_____LZZ=_.a.___YZ(this.______LZ+"/"+this.board_style+"/"+this.____bZZ+".png");}
v._rZ(this.__SZZ,{position:"absolute",width:board_size,height:board_size,backgroundImage:_____LZZ});var _____yZ;for(var wZZZZ=0;wZZZZ<this._____WZ.length;wZZZZ++){_____yZ=this._____WZ[wZZZZ];v._rZ(_____yZ.FZZ,{width:this.____bZZ,height:this.____bZZ,backgroundColor:"#"+this.______MZ[_$ZZZ.______W(wZZZZ)]});this.____mZZ(_____yZ,wZZZZ);v._rZ(_____yZ.pZZ,{width:this.____bZZ,height:this.____bZZ});v._rZ(_____yZ._____AZZ,{width:this.____bZZ-(this.______NZ*2),height:this.____bZZ-(this.______NZ*2),borderWidth:this.______NZ});}
this._bZZZZZ();var _____h=this.____bZZ*4;this._uZZZ.___mZZZ([_____h,_____h],true);this.___vZZZ.___mZZZ(_____h,_____h);this.___dZZZ.___mZZZ(_____h,_____h);}
_fZZZ.prototype.DZZZZ=function(wZZZZ,FZZZZ){__WZZ.prototype.DZZZZ.call(this,wZZZZ,FZZZZ);if(this.______OZ){this._cZZZZZ(wZZZZ,FZZZZ);}}
_fZZZ.prototype._cZZZZZ=function(wZZZZ,FZZZZ){var _____LZZ="none";if(FZZZZ!==zZZZZ){_____LZZ=_.a.___YZ(this.____cZZ+"/"+this.piece_style+"/"+this.____bZZ+"/"+_WZZZ.____yZ(FZZZZ)+".png");}
if(this._____WZ[wZZZZ].pZZ.style.backgroundImage!==_____LZZ){this._____WZ[wZZZZ].pZZ.style.backgroundImage=_____LZZ;}}
_fZZZ.prototype._bZZZZZ=function(){for(var wZZZZ=0;wZZZZ<this.__WZZ.length;wZZZZ++){this._cZZZZZ(wZZZZ,this.__WZZ[wZZZZ]);}}
_fZZZ.prototype.____aZZ=function(){this._dZZZ={_eZZZ:_fZZZ._gZZZ,_qZZ:false,_____MZZ:false,_aZZZ:null,_mZZZ:null,____tZZ:0,____uZZ:0};}
_fZZZ.prototype._____NZZ=function(r,_____OZZ,_____PZZ){_____PZZ=_____PZZ||[this._dZZZ.____tZZ,this._dZZZ.____uZZ];var __PZ=r.pageX;var __QZ=r.pageY;if(_____OZZ){__PZ+=(Math.round(this.____bZZ/2)-_____PZZ[_oZ]);__QZ+=(Math.round(this.____bZZ/2)-_____PZZ[_pZ]);}
var _kZ=v._qZ(this.__SZZ);return this._eZZZZZ(__PZ-_kZ[_oZ],this._____DZZ()-(__QZ-_kZ[_pZ]));}
_fZZZ.prototype._eZZZZZ=function(__PZ,__QZ){var ____CZ=(__PZ-(__PZ%this.____bZZ))/this.____bZZ;var ____BZ=(__QZ-(__QZ%this.____bZZ))/this.____bZZ;if(this.______KZ==kZZZZ){____CZ=7-____CZ;____BZ=7-____BZ;}
return _$ZZZ.______V(____CZ,____BZ);}
_fZZZ.prototype.____mZZ=function(_____yZ,wZZZZ){var __PZ,__QZ;var ____BZ=_$ZZZ.__QZ(wZZZZ);var ____CZ=_$ZZZ.__PZ(wZZZZ);if(this.______KZ==kZZZZ){__PZ=this.____bZZ*(7-____CZ);__QZ=this.____bZZ*____BZ;}
else{__PZ=this.____bZZ*____CZ;__QZ=this.____bZZ*(7-____BZ);}
v._rZ(_____yZ.FZZ,{top:__QZ,left:__PZ});}
_fZZZ.prototype.____nZZ=function(_____yZ){v._rZ(_____yZ.pZZ,{top:0,left:0});}
_fZZZ.prototype.____oZZ=function(_____yZ,__PZ,__QZ){var _kZ=v._qZ(_____yZ.FZZ);v._rZ(_____yZ.pZZ,{top:__QZ-_kZ[_pZ],left:__PZ-_kZ[_oZ]});}
_fZZZ.prototype.____iZZ=function(r){r.preventDefault();if(this.____wZZ(r)){var wZZZZ=this._____NZZ(r);var _____yZ=this._____WZ[wZZZZ];var _kZ=v._qZ(_____yZ.FZZ);if(this._____ZZ!==_fZZZ.______VZ&&!this._dZZZ._qZZ&&!this._dZZZ._____MZZ&&this.__WZZ[wZZZZ]!==zZZZZ){this.____xZZ(_____yZ);this._dZZZ._qZZ=true;this._dZZZ._mZZZ=wZZZZ;this._dZZZ._aZZZ=this.__WZZ[wZZZZ];this._dZZZ.____tZZ=r.pageX-_kZ[_oZ];this._dZZZ.____uZZ=r.pageY-_kZ[_pZ];}}}
_fZZZ.prototype.____kZZ=function(r){r.preventDefault();var wZZZZ=this._____NZZ(r);this._____vZZ(r);this._____QZZ(r);var _____RZZ;if(this._dZZZ._qZZ&&!this._dZZZ._____MZZ){_____RZZ={_____SZZ:wZZZZ,_aZZZ:this.__WZZ[wZZZZ],____sZZ:true,_bZZZ:false};this.__XZZ.t(_____RZZ);if(_____RZZ._bZZZ){this.____aZZ();this.____zZZ(this._____WZ[wZZZZ]);}
else{this._dZZZ._eZZZ=_fZZZ.____$ZZ;this._dZZZ._____MZZ=true;this._cZZZ.t({_iZZZ:wZZZZ});}}
if(this._dZZZ._qZZ&&this._dZZZ._eZZZ===_fZZZ.____$ZZ){_____RZZ={_____SZZ:wZZZZ,_aZZZ:this._dZZZ._aZZZ,_bZZZ:false};this.______oZ.t(_____RZZ);if(!_____RZZ._bZZZ){this.____oZZ(this._____WZ[this._dZZZ._mZZZ],r.pageX-this._dZZZ.____tZZ,r.pageY-this._dZZZ.____uZZ);}}}
_fZZZ.prototype.____jZZ=function(r){r.preventDefault();var _____RZZ;var wZZZZ=this._____NZZ(r);if(this._dZZZ._____MZZ&&this._dZZZ._eZZZ===_fZZZ.____$ZZ){wZZZZ=this._____NZZ(r,true,[this._dZZZ.____tZZ,this._dZZZ.____uZZ]);}
var _____yZ=this._____WZ[wZZZZ];var ____yZZ=null;if(this._dZZZ._mZZZ!==null){____yZZ=this._____WZ[this._dZZZ._mZZZ];}
_____RZZ={_____SZZ:wZZZZ,_dZZZ:this._dZZZ,_bZZZ:false,h:r};if(this._dZZZ._eZZZ===_fZZZ._gZZZ){this.______rZ.t(_____RZZ);}
else if(this._dZZZ._eZZZ===_fZZZ.____$ZZ&&this._dZZZ._____MZZ){this.______nZ.t(_____RZZ);}
if(!_____RZZ._bZZZ){if(this._dZZZ._____MZZ){this._jZZZ.t();if(this.____wZZ(r,true)){if(wZZZZ!=this._dZZZ._mZZZ){this._lZZZ.t({_mZZZ:this._dZZZ._mZZZ,_nZZZ:wZZZZ,_aZZZ:this.EZZZZ(this._dZZZ._mZZZ),h:r});}}
else{this.______qZ.t({_mZZZ:this._dZZZ._mZZZ});}
this.____nZZ(____yZZ);this.____aZZ();}
else if(this._____ZZ&_fZZZ._gZZZ&&this._dZZZ._qZZ&&wZZZZ===this._dZZZ._mZZZ&&!this._dZZZ._____MZZ){_____RZZ={_____SZZ:wZZZZ,_aZZZ:this.__WZZ[wZZZZ],____sZZ:false,_bZZZ:false};this.__XZZ.t(_____RZZ);if(_____RZZ._bZZZ){this.____aZZ();}
else{this._dZZZ._____MZZ=true;this._dZZZ._eZZZ=_fZZZ._gZZZ;this._cZZZ.t({_iZZZ:wZZZZ});}}}
else{if(____yZZ!==null){this.____nZZ(____yZZ);}
this.____aZZ();}
if(____yZZ!==null){this.____zZZ(____yZZ);}
this._____QZZ(r);}
_fZZZ.prototype.____xZZ=function(_____yZ){v._rZ(_____yZ.pZZ,{zIndex:_fZZZ.____AZZ});}
_fZZZ.prototype.____zZZ=function(_____yZ){v._rZ(_____yZ.pZZ,{zIndex:_fZZZ.____BZZ});}
_fZZZ.prototype.____wZZ=function(r,_____OZZ,_____PZZ){_____PZZ=_____PZZ||[this._dZZZ.____tZZ,this._dZZZ.____uZZ];var __PZ=r.pageX;var __QZ=r.pageY;if(_____OZZ){__PZ+=(Math.round(this.____bZZ/2)-_____PZZ[_oZ]);__QZ+=(Math.round(this.____bZZ/2)-_____PZZ[_pZ]);}
var _kZ=v._qZ(this.__SZZ);__PZ-=_kZ[_oZ];__QZ-=_kZ[_pZ];__QZ=this._____DZZ()-__QZ;return this._____TZZ(__PZ,__QZ);}
_fZZZ.prototype._____TZZ=function(__PZ,__QZ){return!(__PZ<0||__PZ>this._____DZZ()||__QZ<0||__QZ>this._____DZZ());}
_fZZZ.prototype._____UZZ=function(wZZZZ,style){v._rZ(this._____WZ[wZZZZ]._____AZZ,style);}
_fZZZ.prototype._____VZZ=function(wZZZZ){if(wZZZZ!==null){v._rZ(this._____WZ[wZZZZ]._____AZZ,this.______WZ);}}
_fZZZ.prototype._____WZZ=function(_____XZZ){for(var O=0;O<this.______xZ.length;O++){this._____VZZ(this.______xZ[O]);}
this.______xZ=_____XZZ;for(var O=0;O<this.______xZ.length;O++){this._____UZZ(this.______xZ[O],this.______XZ);}}
_fZZZ.prototype._____YZZ=function(wZZZZ){this._____VZZ(this.______yZ);this.______yZ=wZZZZ;this._____UZZ(wZZZZ,this.______YZ);}
_fZZZ.prototype._____ZZZ=function(wZZZZ){this._____VZZ(this.______zZ);this.______zZ=wZZZZ;this._____UZZ(wZZZZ,this.______ZZ);}
_fZZZ.prototype.____$ZZZ=function(wZZZZ){this._____VZZ(this.______AZ);this.______AZ=wZZZZ;this._____UZZ(wZZZZ,this._____bZZ);}
_fZZZ.prototype.____aZZZ=function(wZZZZ){this._____VZZ(this.______BZ);this.______BZ=wZZZZ;this._____UZZ(wZZZZ,this._____cZZ);}
_fZZZ.prototype._hZZZ=function(wZZZZ){this._____VZZ(this.______CZ);this.______CZ=wZZZZ;this._____UZZ(wZZZZ,this._____dZZ);}
_fZZZ.prototype.____bZZZ=function(){for(var O=0;O<this.______xZ.length;O++){this._____VZZ(this.______xZ[O]);}
this.______xZ=[];}
_fZZZ.prototype.____cZZZ=function(){this._____VZZ(this.______yZ);this.______yZ=null;}
_fZZZ.prototype.____dZZZ=function(){this._____VZZ(this.______zZ);this.______zZ=null;}
_fZZZ.prototype.____eZZZ=function(){this._____VZZ(this.______AZ);this.______AZ=null;}
_fZZZ.prototype.____fZZZ=function(){this._____VZZ(this.______BZ);this.______BZ=null;}
_fZZZ.prototype._kZZZ=function(){this._____VZZ(this.______CZ);this.______CZ=null;}
_fZZZ.prototype._____DZZ=function(){return this.____bZZ*8;}
_fZZZ.prototype._____vZZ=function(r){var wZZZZ=this._____NZZ(r);if(this.____wZZ(r)&&wZZZZ>-1&&wZZZZ<64){if(this.______lZ!=wZZZZ){if(this.______lZ!==null){this.______tZ.t({_iZZZ:this.______lZ});}
this.______lZ=wZZZZ;this.______sZ.t({_iZZZ:wZZZZ});}}
else{if(this.______lZ!==null){this.______tZ.t({_iZZZ:this.______lZ});}
this.______lZ=null;}}
_fZZZ.prototype._____QZZ=function(r){var wZZZZ=this._____NZZ(r,true);if(this._dZZZ._____MZZ&&this._dZZZ._eZZZ==_fZZZ.____$ZZ){if(this.____wZZ(r)){if(this.______mZ!=wZZZZ){if(this.______mZ!==null){this.______vZ.t({_iZZZ:this.______mZ});}
this.______mZ=wZZZZ;this.______uZ.t({_iZZZ:wZZZZ});}}
else{if(this.______mZ!==null){this.______vZ.t({_iZZZ:this.______mZ});}
this.______mZ=null;}}
else{if(this.______mZ!==null){this.______vZ.t({_iZZZ:this.______mZ});}
this.______mZ=null;}}
_fZZZ.prototype._CZZ=function(){if(this._dZZZ._____MZZ){this.____zZZ(this._____WZ[this._dZZZ._mZZZ]);this.____aZZ();}}
_fZZZ.prototype._oZZZ=function(fen){__WZZ.prototype._oZZZ.call(this,fen);this._bZZZZZ();}
_fZZZ.prototype.____gZZZ=function(piece,fs,ts,____hZZZ){if(___w(____hZZZ)){____hZZZ();}}
_fZZZ.prototype._____tZZ=function(____iZZZ){var ____jZZZ=[this.______FZ,this.______GZ][____iZZZ];return(this._____DZZ()
+this.border.length*2
+(this.______PZ?____jZZZ:0)
+(this.______EZ?____jZZZ:0)
+(this.______PZ?(this.______SZ*2):0));}